version: '3.7'

services:
  ferro-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ferro-web
    container_name: ferro-teste2
    restart: unless-stopped
    networks:
      - scripts_nginx-net
    environment:
      - VIRTUAL_HOST=teste3.hubstock.com.br
      - LETSENCRYPT_HOST=teste3.hubstock.com.br
      - LETSENCRYPT_EMAIL=gabrielc.machado@hotmail.com
    volumes:
      - ./dist:/usr/share/nginx/html

networks:
  scripts_nginx-net:
    name: scripts_nginx-net
    external: true
